Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace DependencyInjectionExample.Models {
    public class ApplicationDbContext : DbContext {
        public DbSet<Character> Characters { get; set; }

        public ApplicationDbContext (DbContextOptions<ApplicationDbContext> options) : base (options) { }

        protected override void OnModelCreating (ModelBuilder builder) {
            base.OnModelCreating (builder);
        }
    }
}

Models/Character.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DependencyInjectionExample.Models {
    public class Character {

        [Key]
        public Guid Id { get; private set; } = Guid.NewGuid ();

        public string Name { get; private set; } = String.Empty;

        public Character (string name) {
            Name = name;
        }

        private Character(){
            //inorder for EF Core to initiate the Character Instance.
        }
    }
}

Models/CharacterRepository.cs
using System.Collections.Generic;
using System.Linq;
using DependencyInjectionExample.Interfaces;

namespace DependencyInjectionExample.Models {
    public class CharacterRepository : ICharacterRepository {
        private readonly ApplicationDbContext _dbContext;

        public CharacterRepository (ApplicationDbContext dbContext) {
            _dbContext = dbContext;
        }

        public void Add (Character character) {
            _dbContext.Characters.Add (character);
            _dbContext.SaveChanges ();
        }

        public IEnumerable<Character> ListAll () {
            return _dbContext.Characters.AsEnumerable ();
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace DependencyInjectionExample.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Operation.cs
using System;
using DependencyInjectionExample.Interfaces;

namespace DependencyInjectionExample.Models {
    public class Operation:
        IOperationTransient, IOperationScoped, IOperationSingleton, IOperationSingletonInstance {

            public Operation () : this (Guid.NewGuid ()) { }

            public Operation (Guid guid) {
                OperationId = guid;
            }

            public Guid OperationId { get; private set; }
        }
}

Controllers/CharactersController.cs
using System;
using System.Linq;
using DependencyInjectionExample.Interfaces;
using DependencyInjectionExample.Models;
using Microsoft.AspNetCore.Mvc;

namespace DependencyInjectionExample.Controllers {
    public class CharactersController : Controller {
        private readonly ICharacterRepository _characterRepository;

        public CharactersController (ICharacterRepository characterRepository) {
            _characterRepository = characterRepository;
        }

        public IActionResult Index () {
            PopulateCharactersIfNoneEXist ();
            var characters = _characterRepository.ListAll ();

            return View (characters);
        }

        private void PopulateCharactersIfNoneEXist () {
            if (!_characterRepository.ListAll ().Any ()) {
                _characterRepository.Add (new Character ("Darth Maul"));
                _characterRepository.Add (new Character ("Darth Vader"));
                _characterRepository.Add (new Character ("Yoda"));
                _characterRepository.Add (new Character ("Mace Windu"));
            }
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace DependencyInjectionExample.Controllers {
    public class HomeController : Controller {
        public IActionResult Index () {
            return View ();
        }

        public IActionResult About () {
            ViewData["Message"] = "Your application description page.";

            return View ();
        }

        public IActionResult Contact () {
            ViewData["Message"] = "Your contact page.";

            return View ();
        }
    }
}

Controllers/OperationsController.cs
using DependencyInjectionExample.Interfaces;
using DependencyInjectionExample.Services;
using Microsoft.AspNetCore.Mvc;

namespace DependencyInjectionExample.Controllers
{
    public class OperationsController : Controller
    {
         private readonly OperationService _operationService;
        private readonly IOperationTransient _transientOperation;
        private readonly IOperationScoped _scopedOperation;
        private readonly IOperationSingleton _singletonOperation;
        private readonly IOperationSingletonInstance _singletonInstanceOperation;

        public OperationsController(OperationService operationService,
            IOperationTransient transientOperation,
            IOperationScoped scopedOperation,
            IOperationSingleton singletonOperation,
            IOperationSingletonInstance singletonInstanceOperation)
        {
            _operationService = operationService;
            _transientOperation = transientOperation;
            _scopedOperation = scopedOperation;
            _singletonOperation = singletonOperation;
            _singletonInstanceOperation = singletonInstanceOperation;
        }

        public IActionResult Index()
        {
            // viewbag contains controller-requested services
            ViewBag.Transient = _transientOperation;
            ViewBag.Scoped = _scopedOperation;
            ViewBag.Singleton = _singletonOperation;
            ViewBag.SingletonInstance = _singletonInstanceOperation;
            
            // operation service has its own requested services
            ViewBag.Service = _operationService;
            return View();
        }
    }
}

Views/Characters/Index.cshtml
@using System.Threading.Tasks
@using DependencyInjectionExample.Models
@model IEnumerable<DependencyInjectionExample.Models.Character>
@{
    ViewData["Title"] = "Characters";
}
<h1>Characters</h1>
<div class="row">
    <div class="col-md-12">
        <table>
            <tr>
                <th>Name</th>
            </tr>
            @foreach (var character in Model)
            {
                <tr>
                    <td>@character.Name</td>
                </tr>
            }
            <tr>
            </tr>
        </table>
    </div>
</div>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<h2>Examples:</h2>
<ul>
    <li><a asp-controller="Characters" asp-action="Index">Characters</a></li>
    <li><a asp-controller="Operations" asp-action="Index">Operations</a></li>
</ul>

Views/Operations/Index.cshtml
@using System.Threading.Tasks
@using DependencyInjectionExample.Interfaces
@{
    ViewData["Title"] = "Lifetimes";
}
<h1>Lifetimes</h1>
<div class="row">
    <div class="col-md-6">
        Controller Operations
        <dl class="dl-horizontal">
            <dt>Transient</dt>
            <dd>@ViewBag.Transient.OperationId</dd>
            <dt>Scoped</dt>
            <dd>@ViewBag.Scoped.OperationId</dd>
            <dt>Singleton</dt>
            <dd>@ViewBag.Singleton.OperationId</dd>
            <dt>Singleton (Instance)</dt>
            <dd>@ViewBag.SingletonInstance.OperationId</dd>
        </dl>
    </div>
    <div class="col-md-6">
        OperationService Operations
        <dl class="dl-horizontal">
            <dt>Transient</dt>
            <dd>@ViewBag.Service.TransientOperation.OperationId</dd>
            <dt>Scoped</dt>
            <dd>@ViewBag.Service.ScopedOperation.OperationId</dd>
            <dt>Singleton</dt>
            <dd>@ViewBag.Service.SingletonOperation.OperationId</dd>
            <dt>Singleton (Instance)</dt>
            <dd>@ViewBag.Service.SingletonInstanceOperation.OperationId</dd>
        </dl>

    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DependencyInjectionExample</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DependencyInjectionExample</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - DependencyInjectionExample</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>